### ISSUE TITLE
Restrictions Screen - Update Map zoom and colors

### ISSUE THREAD

**Issue by felimartina** [CodeforHawaii/ACLU#133]
When the user enters the Restrictions Screen there are a few things that will happen:

1. Map view will be zoomed in to show the currently selected polygon along with surrounding polygons.
2. Selected Polygon will be highlighted according to designs
3. Unselected Polygons will be greyed out
4. The user should be able to select a different polygon by tap/click (only one polygon selected at a time)

**Comment by warent** [comment]
Done! 🎉
