### ISSUE TITLE
Add animation to spinner/loading component

### ISSUE THREAD

**Issue by felimartina** [CodeforHawaii/ACLU#161]
We created a `Loading` component to use every time we are doing some async processing (like https calls to the backend api).
Right now we only show holo holo logo in there. It will be nice to add some animation to that loading screen so that the user understands that there is something going on behind the scenes.

Use GSAP and the following article to implement:

https://blog.usejournal.com/vue-js-gsap-animations-26fc6b1c3c5a

**Comment by bronsonavila** [comment]
Would I be able to be assigned to this task?  I was able to integrate the animations from the referenced blog into the Loading component's spinner-image.  See: [https://github.com/bronsonavila/ACLU/blob/ba-spinner/frontend-v2/src/components/Loading.vue](https://github.com/bronsonavila/ACLU/blob/ba-spinner/frontend-v2/src/components/Loading.vue).  If this appears acceptable, I can submit a PR for further review.

**Comment by felimartina** [comment]
Hey @bronsonavila, sorry for this super late reply!
Yes man, go ahead and take it. I checked out what you did...pretty cool!
Go ahead and submit a PR!!!

Great job :)

**Comment by bronsonavila** [comment]
Thanks. PR submitted.
