### ISSUE TITLE
Determine Accessibility Needs

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#20]

**Comment by mckaydavis** [comment]
from @rbvea: this is a great tool for testing accessibility on webpages: https://addyosmani.com/a11y/

**Comment by mckaydavis** [comment]
ref to #75
also @tiktnarg mentioned:

Bobby: http://www.coggan.com/bobby-approved.html

and this ACLU site: https://www.aclu.org/issues/disability-rights

**Comment by warent** [comment]
Closing this as stale and out of date.
