### ISSUE TITLE
State Sheriff Jurisdiction 

### ISSUE THREAD

**Issue by derandecker** [CodeforHawaii/ACLU#24]
Reach out to Sheriff's office to try to get data

**Comment by mckaydavis** [comment]
@tiktnarg is going to reach out to the Hawaii Department of Public Safety to inquire if they have this data.

**Comment by mckaydavis** [comment]
https://en.wikipedia.org/wiki/Hawaii_Department_of_Public_Safety#Sheriff_Division has some information on areas.  For example (from the article):
> The Capitol Section provides an immediate law enforcement presence at the Hawaii State Capitol, Hawaii Civic Center Complex, Washington Place, and other locations deemed necessary by factors other than public safety related statistics. A recent agreement (2013) between the Sheriff Division and the Hawaii Community Development Association (HCDA) placed stipulations that the Sheriffs provide Law Enforcement for the Kaka'ako area as well as Kewalo Basin. Deputies have also been tasked with providing patrols at the Mayor Rights Public Housing Complexes. Deputies, arrest and or cite violators of statutes or ordinances during vehiclular patrol.

**Comment by mckaydavis** [comment]
After discussion with @tiktnarg, it may be the case that the State Sheriff has jurisdiction anywhere in the state.  We may need to identify which properties/boundaries are specifically covered by the dept. (e.g. libraries, courthouses, & other state buildings).
