### ISSUE TITLE
City Park Hours

### ISSUE THREAD

**Issue by derandecker** [CodeforHawaii/ACLU#26]
Create spreadsheet with list of city parks and hours. Contact city to see if we can get this info.

**Comment by mckaydavis** [comment]
City park hours just recently had a change.  It also looks like some areas of the park (e.g. Basketball Courts) now have separate / shorter hours than the rest of the park.

Reference: http://khon2.com/2017/08/22/changes-to-public-park-hours-aim-to-reduce-illegal-activity-noise-complaints/

**Comment by rbvea** [comment]
It'd be interesting to have a notification saying "no ball playing" when you open up the app but that seems outside of scope.

**Comment by rbvea** [comment]
We have this for park hours, we need to maybe scrape this site and pair it up with the geojson file we're importing into the db: https://www.honolulu.gov/parks/default/park-closure-hours.html

**Comment by mckaydavis** [comment]
see #51

**Comment by mckaydavis** [comment]
Just a note that the data at https://www.honolulu.gov/parks/default/park-closure-hours.html looks to be fairly up to date.  The original news story above was published on Aug 22nd, and the park hours site was updated August 25th.  The table also includes hours specifically for the basketball courts.
