### ISSUE TITLE
Get CCHNL Sit/Lie Ban Boundary data

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#3]

**Comment by mckaydavis** [comment]
In [this November 12, 2014 Civil Beat article](http://www.civilbeat.org/2014/11/honolulu-city-council-postpones-vote-to-expand-sit-lie-ban-until-friday/) there is a link to [scans of the Honolulu City Council Sit/Lie Ban boundaries](https://www.slideshare.net/civilbeat/scan-nov-12-2014-356-pm).

In case URLs change, attached is a highly compressed (22MB -> 2MB) version of the [Honolulu sit/lie ban map PDF scannov1220143-141112205940-conversion-gate02_optimized.pdf](https://github.com/CodeforHawaii/ACLU/files/1146443/scannov1220143-141112205940-conversion-gate02_optimized.pdf)

The next step is to find a digital version of these boundaries.

**Comment by mckaydavis** [comment]
The zones are codified in the [City and County of Honolulu Ordinance 14-35](http://www4.honolulu.gov/docushare/dsweb/Get/Document-151078/BILL048(14).htm) (originally introduced as Bill 48(2014)).

The text of the bill specifies the boundaries in english.

Exhibits 1 through 13 of the [signed ordinance PDF](http://www4.honolulu.gov/docushare/dsweb/Get/Document-153805/DOC002%20(45).PDF) show the codified boundaries as maps prepared by the Office of Council Services for the City Council.

**Comment by mckaydavis** [comment]
I emailed Ken Schmidt @ CCHNL and requested the GIS data as prepared by the Office of Council Services.

**Comment by mckaydavis** [comment]
The zones were expanded in 2015 with the introduction of [Bill 6(2015)](http://www4.honolulu.gov/docushare/dsweb/Get/Document-161737/BILL006\(15\).htm) that became codified in [City and County of Honolulu Ordinance 15-14](http://www4.honolulu.gov/docushare/dsweb/Get/Document-166012/DOC002%20(19).PDF).

Exhibits 2 through 15 on pages 13-18 of the PDF show the expanded boundary maps.

My request to Ken Schmidt did not request these zones.  I'm going to wait for his response to my previous request for the Ordinance 14-35 GIS data before pursuing the request for data of these expanded boundaries.

**Comment by mckaydavis** [comment]
After thinking about the street shapes displayed in the ordinance PDFs it occurs to me that they are likely not detailed enough to demarcate exact boundaries of where the ban would be enforced.  My guess is any street GIS data provided by the city will only consist of a line segment.  i.e. it will not be an enclosed polygon that we can test if the query point is inside of. 

At the end of the day, we may need to manually draw the boundaries.  An alternative is to test distance to the line segment and display a warning / explanation if the query point nearby or possibly inside a zone covered by the ordinances.

**Comment by mckaydavis** [comment]
[Bill 62(2014)](http://www4.honolulu.gov/docushare/dsweb/Get/Document-152701/BILL062(14).htm) was enacted as [Ordinance 15-1](http://www4.honolulu.gov/docushare/dsweb/Get/Document-161745/dspage07500950716899260828.pdf).

Briefly, the ordinance specifies sit/lie ban areas for Fort Street Mall, Kekaulike Mall, Sun Yat Sen Mall, Union Mall during certain hours (5:00am to 7:00pm). 

The bill does not provide maps as the areas are specified in the Revised Ordinances of Honolulu (ROH).

From the bill text: 
```
“Fort Street Mall” means the portion of Fort Street established as a pedestrian
mall under Section 15-25.1b.
“Kekaulike Mall” means the area of Kekaulike Street, between Hotel Street and
King Street.
“Mall,” when used generally in this article, means collectively the Fort Street Mall,
Kekaulike Mall, Sun Yat Sen Mall, and Union Mall.
“Sun Yat Sen Mall” means the same as “Sun Yat Sen Mall” in Section 29-1.1.
“Union Mall” means the portion of Union Street established as a pedestrian mall
under Section 15-25.1a.
```

**Comment by mckaydavis** [comment]
[Bill 44(2015)](http://www4.honolulu.gov/docushare/dsweb/Get/Document-165653/BILL044(15).htm) was enacted as [Ordinance 15-40](http://www4.honolulu.gov/docushare/dsweb/Get/Document-168640/DOC004%20(12).PDF).

The ordinance expands upon 15-1's hours while also adding College Walk Mall and Kila Kalikimaka Mall.

15-40.d has the pertinent bits:
```
(d) As used in this section:
“College Walk Mall” means the same as “College Walk Mall” in Section 29-1.1.
“Expressive activity” means speech or conduct, the principal object of which is
the expression, dissemination, or communication by verbal, visual, literary, or auditory
means of political, religious, philosophical, or ideological opinions, views, or ideas, and
for which no fee is charged or required as a condition of participation in or attendance at
such activity. Expressive activity generally would not include sports events, such as
marathons; fundraising events; beauty contests; commercial events; cultural
celebrations or other events the principal purpose of which is entertainment.
“Fort Street Mall” means the portion of Fort Street established as a pedestrian
mall under Section 15-25.1(b).
“Kekaulike Mall” means the area of Kekaulike Street, between Hotel Street and
King Street.
“Kila Kalikimaka Mall” means the area immediately adiacent to the parcel
designated by TMK 1-7-026:010, from College Walk Mall to Aala Street.
“Mall,” when used generally in this article, means collectively the College Walk
Mall. Fort Street Mall, Kekaulike Mall, Kila Kalikimaka Mall, Sun Yat Sen Mall, and
Union Mall.
“Sun Yat Sen Mall” means the same as “Sun Yat Sen Mall” in Section 29-1.1.
“Union Mall” means the portion of Union Street established as a pedestrian mall
under Section 15-25.1(a).”
```

**Comment by mckaydavis** [comment]
I'm not sure if this belongs in this issue or not, but documenting here as it's related:

[Bill 54(2011)](http://www4.honolulu.gov/docushare/dsweb/Get/Document-117324/BILL054(11).htm) was enacted as [Ordinance 11-29](http://www4.honolulu.gov/docushare/dsweb/Get/Document-120081/6jlmb8hx.pdf)

_**SECTION 1.** Purpose. The purpose of this ordinance is to establish a procedure
for the removal and disposal of personal property stored on public property._

**Comment by mckaydavis** [comment]
[Bill 13(2017)](http://www4.honolulu.gov/docushare/dsweb/Get/Document-190102/BILL013(17).htm) was enacted as [Ordinance 17-15](http://www4.honolulu.gov/docushare/dsweb/Get/Document-194165/DOC007%20(36).PDF) on 05/11/2017.

_SECTION 1. Purpose. The purpose of this ordinance is to amend the law
relating to sitting or lying on public sidewalks in areas zoned for commercial and
business activities to include certain sidewalks in Kalihi and lwilei._

Exhibits 16 and 17 on pages 13-14 of the PDF show the expanded boundaries.

Related Feb 22, 2017 Civil Beat article _[More Sit-Lie Bans Advance In Honolulu City Council](http://www.civilbeat.org/2017/02/more-sit-lie-bans-advance-in-honolulu-city-council/)_.

**Comment by mckaydavis** [comment]
I need to verify, but it appears all of the above bills are aggregated under the [Revised Ordinances of Honolulu Chapter 29, Article 15](https://www.honolulu.gov/cms-ocs-menu/site-ocs-sitearticles/21317-roh-chapter-29.html), including the maps of [Exhibits 1 through 15](https://www.honolulu.gov/rep/site/ocs/roh/ROH_Chapter_29_Article_15A_Exhibits1-15_Sit_Lie_Prohibitions_Outside_of_Waikiki_Special_District.pdf)

**Comment by mckaydavis** [comment]
I emailed Ken Schmidt again and modified my request to _"the GIS data of the boundaries specified in the Revised Ordinances of Honolulu, Chapter 29, Article 15A, Exhibits 1 through 17."_

Ken replied and said he would need a few days to review and that someone would get back by Monday (July 24th).

**Comment by mckaydavis** [comment]
Update:
On July 31st, Arleen Oshiri at the CCHNL GIS office asked me to forward my request to Lori M. Hiraoka, Staff Attorney at the Office of Council Services.

I did, and received an immediate email response of "OCS has received your request and will respond shortly."

**Comment by mckaydavis** [comment]
Email response from Lori Hiraoka on August 8th:
> OCS has researched your request for the GIS data of the boundaries specified in ROH Chapter 29, Article 15A, Exhibits 1 through 17 (the “sit-lie” ordinance).  Unfortunately, there is no central file in our office for preliminary drafts of maps, only the final PDFs versions, so OCS does not have a record of the data you are requesting.
> 
> OCS does not have a ‘final’ data file of the sit-lie maps as adopted by the Council. OCS uses the ArcMap program to create the maps but any files created are working documents/files. OCS does not create a final data file after the Council approves the maps.  The final approved maps are in PDF form, and are available online from the City Council’s website or from the online version of the ROH.
> 
> OCS looked at the data files that we do have, and the data files do not accurately depict the areas approved by the Council for the sit-lie ordinance. For example: some zones and street segments are missing, some zones are from prior drafts, and some zones are drawn where there are no prohibitions.
> 
> If Code for Hawaii would like GIS maps of the zones, it appears that the best alternative may be to use the official maps to create a data file.
>  
> In addition, OCS does not have the latitude and longitude coordinates for the map zones because we did not use them to generate the zones.

**Comment by rbvea** [comment]
So basically we'd have to trace the PDF's with some tool or something?

**Comment by mckaydavis** [comment]
Maybe... but to obtain highest accuracy with respect to the actual law it might be better to attempt to recreate the zones as specified in text of the ordinances themselves....

For example, [Ordinance 17-15](http://www4.honolulu.gov/docushare/dsweb/Get/Document-194165/DOC007%20(36).PDF) describes the zone for Kailua as follows:
```
(4) Kailua. The Kailua zone is the area of the city bounded by the following
streets as illustrated in Exhibit 4:
- Starting at the intersection of Kainehe Street/Kihapai Street,
- Kihapai Street to the intersection of Kihapai Street/Oneawa Street,
- Oneawa Street to the intersection of Oneawa StreetlUluniu Street,
- Uluniu Street to the intersection of Uluniu Street/Maluniu Avenue,
- Maluniu Avenue to the intersection of Maluniu Avenue/Kuulei Road,
- Kuulei Road to the intersection of Kuulei Road/Oneawa Street/Kailua
Road,
- Oneawa Street/Kailua Road to the intersection of Kailua Road/Hahani
Street,
- Hahani Street to the intersection of Hahani Street/Hekili Street,
- Hekili Street to the intersection of Hekili StreetlHamakua Drive/Kainehe
Street, and
- Hamakua Drive/Kainehe Street to the intersection of Kainehe
Street/Kihapai Street.
The Kailua zone also includes the sidewalks abutting the following street
segments:
- Oneawa Street beginning at the intersection of Oneawa
Street/Kawainui Street and ending at the intersection of Oneawa
Street/Ulunui Street, and
- Hamakua Drive beginning at the intersection of Hamakua Drive/Hahani
Street and ending at the intersection of Hamakua Drive/Aoloa Street.
```

**Comment by mckaydavis** [comment]
I've responded to Lori asking for the 'prior draft' data files in lieu of the final data.  It should at least provide a start that we can work off of rather than nothing.

**Comment by rbvea** [comment]
If we do have to trace streets, this could be a good tool: https://google-developers.appspot.com/maps/documentation/utils/geojson/

**Comment by mckaydavis** [comment]
> Attached are two SHP files of the zones and the street segments. 
> 
> Please note that this data was used only to create the map attachments to the sit-lie bills that OCS prepares for the Council. The data is not given to the Administration for purposes of enforcing the sit-lie ordinance.
>  
> In addition, the maps are illustrative of the detailed ordinance text descriptions of the zones and street segments.

[Article 15A segments.zip](https://github.com/CodeforHawaii/ACLU/files/1213668/Article.15A.segments.zip)

**Comment by bradbaris** [comment]
Noticed that forks of the Google Geojson tool exist. Something to get into?  https://github.com/tomscholz/geojson-editor

**Comment by bradbaris** [comment]
New York City Department of City Planning apparently has a geojson tool https://github.com/NYCPlanning/simple-geom-editor

**Comment by johnkmzhou** [comment]
Those shapefiles are missing shx and dbf files. I opened it in [http://mapshaper.org](http://mapshaper.org) but the data appears to be lackluster. I tried to open it in [QGIS](http://www.qgis.org) but it returned back an error message: "Invalid Data Source: Article 15A zones.shp is not a valid or recognized data source".

**Comment by mckaydavis** [comment]
I inquired again and received all the necessary `SHP`,`DBF`,`SHX`, and `PRJ` files from Lori today. I converted them to GeoJSON using the commands:
```
ogr2ogr -f GeoJSON -t_srs crs:84 segments.geojson segments.shp
ogr2ogr -f GeoJSON -t_srs crs:84 zones.geojson zones.shp
```

Here's a zipfile of all of the data: 
[ROH.Chapter29.Article15A.GISData.zip](https://github.com/CodeforHawaii/ACLU/files/1226783/ROH.Chapter29.Article15A.GISData.zip)

**Comment by mckaydavis** [comment]
This data needs to be checked against the printed maps referenced above to see if we are missing any sections.

**Comment by mckaydavis** [comment]
After doing a quick eye check, here's a mapping of the feature names to Exhibit #'s:

`Exhibit 1` -> `zones/Chinatown`  
`Exhibit 2` -> `zones/Downtown`
`Exhibit 3` -> `zones/McCully`, `segments/McCully`
`Exhibit 4` -> `zones/Kailua`, `segments/Kailua` (2)
`Exhibit 5` -> `zones/Wahiawa`, `segments/Wahiawa`  
`Exhibit 6-A` -> `zones/Ala Moana A`  
`Exhibit 6-B` -> `zones/Ala Moana B`, `segments/Ala Moana`  
`Exhibit 7-A` -> `zones/Kaneohe A`, `segments/Kaneohe A`  
`Exhibit 7-B` -> `zones/Kaneohe B`  
`Exhibit 8` -> `zones/Waimanalo`  
`Exhibit 9` -> `segments/Kapahulu`
`Exhibit 10` -> `segments/Kaimuki` (2)  
`Exhibit 11` -> `segments/Kahala`  
`Exhibit 12` -> `segments/Aina Haina-Niu` (2)
`Exhibit 13` -> `segments/Hawaii Kai` (3)  
`Exhibit 14` -> `zones/Aala`, `segments/Aala` (2?) see notes
`Exhibit 15` -> `segments/Kapalama`
`Exhibit 16` -> see notes
`Exhibit 17` -> `segments/Aala`, see notes

## Notes:
This check was not exhaustive.  I only visually compared the GeoJSON visualization to the exhibits presented in [here](https://www.honolulu.gov/rep/site/ocs/roh/ROH_Chapter_29_Article_15A_Exhibits1-15_Sit_Lie_Prohibitions_Outside_of_Waikiki_Special_District.pdf) and [here](http://www4.honolulu.gov/docushare/dsweb/Get/Document-194165/DOC007%20\(36\).PDF).  I am not a lawyer, but I assume the zones as described in the textual descriptions codified as ROH, Chapter 29, Article 15A would be the final say.

Here are the data issues on my initial check:
* **Exhibit 14:** The zones shapefile contains an area named `Aala` by the Kapalama Canal that is not shown in the Exhibit 14 map.  This may be covered by another ordinance or exhibit though.
* **Exhibit 16:** The zone in Kahili, (Exhibit 16 of Bill 13(2017), enacted as Ordinance 17-15 on 05/11/2017  is not present in the data.
* **Exhibit 17:** The segments shapefile appears to be missing the segment along Kuwili St. between Pine St and Iwilei Rd.  The ordinance needs to be checked.

**Comment by mckaydavis** [comment]
This data needs to also have the pedestrian mall zones included.  @ryankanno mentioned that the parks dataset has some of these shapes.

**Comment by mckaydavis** [comment]
The boundaries were expanded recently with the mayor signing [bill 66](http://www4.honolulu.gov/docushare/dsweb/Get/Document-196124/BILL066(17)%2c%20CD1.PDF):

[KHON2 news story here](http://khon2.com/2017/08/21/honolulu-mayor-signs-bill-expanding-sit-lie-ban-to-pacific-victoria-streets/)

**Comment by VERNONBALMERJR** [comment]
Can anybody tell me where I can view a map of the areas covered by the current sit-lie ban?

**Comment by mckaydavis** [comment]
@VERNONBALMERJR: as far as I know, there is no online map of the current sit-lie ban boundaries.

That is the intent of this issue: to gather complete and current sit-lie ban boundary in digital format that is suitable for online publication and distribution.

In the comments above, many of the linked `.pdf` files contain scanned maps of the boundaries.  However, scanned PDFs are not sufficient for creating interactive maps -- we need digital lat/lon coordinates.  

I did manage to get a good chunk of the data via a request to CCHNL Corporate Council and have placed it in [this folder holding the sit-lie ban area data](https://github.com/CodeforHawaii/ACLU/tree/master/backend/data/ROH.Chapter29.Article15A/2017.08.15).  [Notes on that data are in this comment](https://github.com/CodeforHawaii/ACLU/issues/3#issuecomment-322961515).

The `.shp` files have been converted to `.geojson` files.  You can preview them in an interactive map from these links:
* [segments.geojson](https://github.com/CodeforHawaii/ACLU/blob/master/backend/data/ROH.Chapter29.Article15A/2017.08.15/segments.geojson)
* [zones.geojson](https://github.com/CodeforHawaii/ACLU/blob/master/backend/data/ROH.Chapter29.Article15A/2017.08.15/zones.geojson)

**Important note: the sit-lie ban areas the linked maps are a subset, and the data is neither complete nor current**

In the time since my research documented above, I believe the sit-lie ban areas have been expanded via more recent ordinances that have been passed by the Honolulu City Council.  Therefore, more research needs to be done to validate the existing data and identify what new datasets we should request from the City.
