### ISSUE TITLE
Create a color palette for the app to use

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#41]

**Comment by rbvea** [comment]
https://www.aclu.org/other/aclu-branding-guide

**Comment by eunjipaulakim** [comment]
![img_1274](https://user-images.githubusercontent.com/31088584/29396591-623aea30-82b4-11e7-8aab-670114cd1279.PNG)
![img_1276](https://user-images.githubusercontent.com/31088584/29396592-62461e8c-82b4-11e7-9dc5-83c665b18c94.PNG)
