### ISSUE TITLE
Choose fonts and typing scale

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#42]

**Comment by eunjipaulakim** [comment]
![img_1287](https://user-images.githubusercontent.com/31088584/29396818-11c8bb3e-82b6-11e7-91b5-15629aed455c.PNG)

Will upload a media asset .zip file for MAC when received. Examples of the type face used for ACLU's website is included below. 
![img_1277](https://user-images.githubusercontent.com/31088584/29397073-ab677d06-82b7-11e7-8f88-ad9c60e932bb.PNG)
![img_1278](https://user-images.githubusercontent.com/31088584/29397077-ab85aace-82b7-11e7-8bf4-4ad0c950a310.PNG)
![img_1279](https://user-images.githubusercontent.com/31088584/29397075-ab847bea-82b7-11e7-9769-575bf57d2903.PNG)
![img_1280](https://user-images.githubusercontent.com/31088584/29397074-ab82de66-82b7-11e7-980b-ce0c7b4731ff.PNG)
![img_1281](https://user-images.githubusercontent.com/31088584/29397076-ab85b9ba-82b7-11e7-9fa9-2193cd888088.PNG)
![img_1283](https://user-images.githubusercontent.com/31088584/29397078-abb0b8ae-82b7-11e7-9ca4-e33122237e60.PNG)

**Comment by bradbaris** [comment]
As far as free alternatives to DIN Pro, Google Fonts has [Ropa Sans](https://fonts.google.com/specimen/Ropa+Sans) and [PT Sans](https://fonts.google.com/specimen/PT+Sans). 

With that, I think the typing scale can be left to the implementor.

**Comment by warent** [comment]
Closing as out of date
