### ISSUE TITLE
Hot reload node

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#47]
Get node to hot reload with nodemon or webpack

**Comment by mckaydavis** [comment]
it looks like the problem is that the vagrant / virtualbox shared dir needs to do polling

**Comment by mckaydavis** [comment]
https://github.com/webpack/webpack/issues/425#issuecomment-53273873

**Comment by rbvea** [comment]
https://webpack.js.org/guides/development-vagrant/
