### ISSUE TITLE
Name the Project

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#5]
Name the project

**Comment by wreppun** [comment]
whereyoustaygo

**Comment by bradbaris** [comment]
Besides a name that makes it clear as to what the app's purpose is, I think it may also be a good idea to borrow some vocabulary from the ACLU brand? I was thinking of keywords like: boundary, zones, access, metaphors, etc. Throwing some random combinations out there to stir inspiration:  ZoneCheck, SafeGround, Beyond Boundaries, BoundarySight, Rights to Sites, LegalSurveyor, Surefooted, Sightline, etc. Additionally, a name that ties into the red/yellow/green 'light' idea of the app might be worth noodling around on too.

**Comment by johnkmzhou** [comment]
"Walkabout" because that was a great episode of Lost.
