### ISSUE TITLE
staging site

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#50]
As a non-technical user, I would like to view the latest state of the app from a url.

The tech side needs to setup an auto-deploy on git checkin.

**Comment by rbvea** [comment]
I wonder if we could use `now` for now?  I still have my paid acct 😬

**Comment by mckaydavis** [comment]
Worth a try, what's the steps?

**Comment by rbvea** [comment]
@mckaydavis if you have a spare moment:

`npm i -g now` should install the command, then you can `now login`.

`now --docker` should deploy the Dockerfile so maybe we can use the one in `backend` then we could have another now instance for the frontend site that points to the `now` hosted backend.  We'd need to: 
* port the Dockerfile from a dev env that uses port 50050 to 80
* stand up a mongo instance
* run scripts to seed the parks data onto that mongo instance

**Comment by rbvea** [comment]
Kit has provided credentials for the ALCU AWS account: https://hicapacity.slack.com/archives/C684A8E03/p1508193030000063

@felimartina what are the steps to deploy?

**Comment by felimartina** [comment]
@rbvea we still need to have the code for env variables in vue.js for the ci/cd pipeline to work properly! But we can still manually deploy it though!

I’m gonna be pushing (tmr surely) a branch with all the automatipn stuff and terraform so we don’t have to manage things manually!
I will take the creds and test the terraform stack and see what may be missing!

**Comment by rbvea** [comment]
@felimartina good to close this out? Seems like https://aclu.codeforhawaii.org/#/ is working well.

**Comment by felimartina** [comment]
yes!!!
