### ISSUE TITLE
Scrape park open hours and tie them to features' property in geojson.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#51]
Scrape hours from site and map them to a features "name" property.

https://www.honolulu.gov/parks/default/park-closure-hours.html

**Comment by johnkmzhou** [comment]
Where, specifically, should I drop the hours data in?

**Comment by rbvea** [comment]
@johnkmzhou so if you ping a route with data, like http://localhost:50050/features/?where={%22geojson.geometry%22:{%22$near%22:{%22$geometry%22:{%22type%22:%22Point%22,%20%22coordinates%22:[-157.861547,%2021.309912]},%20%22$maxDistance%22:%20250}}}

you get a bunch of fake data as of now, but the goal is to associate a feature within the parks geojson and the hours in the table.

**Comment by rbvea** [comment]
Looking at the code, it seems to me that we could do that within the `import_features` function: https://github.com/CodeforHawaii/ACLU/blob/master/backend/importer/import_features.py#L45

e.g. `feature.properties.hours = fetch_park_hours(feature.properties.name)`

**Comment by johnkmzhou** [comment]
What I mean is where in the geojson do you want it?

**Comment by johnkmzhou** [comment]
Some edge cases to think about for a schema change:
```
Hanauma Bay Nature Preserve 
6:00 p.m. - 6:00 a.m. (Winter) 
7:00 p.m. - 6:00 a.m. (Summer)
```
```
Kailua Beach Park
Restroom
10:00 p.m. - 6:00 a.m.
Parking
10:00 p.m. - 5:00 a.m.
Parking 'C'; Boat Ramp Parking
10:00 p.m. - 5:00 a.m.
```

Each section of the park could be considered it's own location. Will also need to figure out date range for Winter and Summer and how that will play a role or we can remove Hanauma Bay because there's a pay barrier.

**Comment by mckaydavis** [comment]
Just referencing this checkin by @johnkmzhou here: https://github.com/CodeforHawaii/ACLU/commit/f1e6b7e267fbe3492c273ab7f311b02ca45deab8

**Comment by mckaydavis** [comment]
http://www.staradvertiser.com/2017/10/03/breaking-news/kakaako-waterfront-park-to-close-indefinitely-as-homeless-population-grows/

The list was updated Oct 3rd, but I don't see Kakaako Waterfront Park in the list.

**Comment by mckaydavis** [comment]
Here's some representative entries that include edge cases now returned by `import_park_features()` after [this checkin](https://github.com/CodeforHawaii/ACLU/commit/f738ef988ba15afdd84c75a17ce5239f324a8a33):
```
examples = {
  "Nanikai Beach Park": {
    "park": {
      "close": 2200,
      "open": 500
    }
  },
  "Kaomaʻaikū Neighborhood Park": {
    "park": {
      "close": "Dusk",
      "open": "Dawn"
    }
  },
  "Kailua Beach Park": {
    "Parking 'C'; Boat Ramp Parking": {
      "close": 2200,
      "open": 500
    },
    "Parking": {
      "close": 2200,
      "open": 500
    },
    "Restroom": {
      "close": 2200,
      "open": 600
    }
  },
  "Hanauma Bay Nature Preserve": {
    "park": {
      "close": 1800,
      "notes": "(Winter)",
      "open": 600
    },
    "Hanauma Bay Nature Preserve": {
      "close": 1900,
      "notes": "(Summer)",
      "open": 600
    }
  }
}
```
