### ISSUE TITLE
Make API endpoint configurable.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#59]
Depending on the environment, point the api either from `localhost:50050` to `[insert server is]`.

**Comment by nihey** [comment]
Can I take this?

As I've seen the best solution for this will most likely have something to do with [this directory](https://github.com/CodeforHawaii/ACLU/tree/master/frontend/config), or you'll need something configurable via `Environment Var`s, using `process.env`?

**Comment by rbvea** [comment]
@nihey thanks for volunteering and sorry for the delay!  I believe we're standing up a production server today but you're free to start on this!  I believe we're setting the environment in the `/build` directory but it's just a matter of checking against process.env.NODE_ENV and changing the api.

**Comment by felimartina** [comment]
@nihey Ideally it will read it from an Environment Var. `process.env` should work!

**Comment by nihey** [comment]
Alright! I'll take a look at it on the weekend :+1:
