### ISSUE TITLE
HTTPS cert for aclu.codeforhawaii.com

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#70]

**Comment by mckaydavis** [comment]
@felimartina Done. The certificate for the `aclu.codeforhawaii.org` subdomain is in the aclu's aws certificate manager (region us-west-1). I've also setup the CNAME for that name to point at `d3t0l1kpp6myc4.cloudfront.net`

**Comment by rbvea** [comment]
FYI https://aclu.codeforhawaii.org produces a cert error and the unsecure page produces a cloudfront error

**Comment by mckaydavis** [comment]
okay yeah, I had closed the issue as I had obtained the cert, but it still needs to be deployed.  We'll also want to make sure `http` on port 80 of `aclu.codeforhawaii.org` correctly redirects to the `https://` url

**Comment by rbvea** [comment]
Ah ok, I'll close this and keep #67 open then.

**Comment by felimartina** [comment]
@mckaydavis site is running on region `us-west-2` (Oregon)...would you mind uploading the cert into that region instead?

**Comment by felimartina** [comment]
I could deploy stack in `us-west-1` with few changes if you guys prefer so.

**Comment by felimartina** [comment]
@mckaydavis Actually...seems like we need to store certificate in `US-EAST-1`
```
If you want to require HTTPS between viewers and CloudFront, you must change the AWS region to US East (N. Virginia) in the AWS Certificate Manager console before you request or import a certificate.
```

Source => http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html

Also says the same in the web console:
```
You can use a certificate stored in AWS Certificate Manager (ACM) in the US East
(N. Virginia) Region, or you can use a certificate stored in IAM.
```

**Comment by mckaydavis** [comment]
@felimartina :ok_hand: cert issued in `us-east-1`

**Comment by felimartina** [comment]
@mckaydavis can we get an `api.aclu.codeforhawaii.org` for the API? we need the API to be HTTPS as well, don't we?

**Comment by mckaydavis** [comment]
@felimartina :ok: cert issued in `us-east-1` for 	`aclu.codeforhawaii.org`,	`api.aclu.codeforhawaii.org`, `api.codeforhawaii.org`, and `www.aclu.codeforhawaii.org`

**Comment by felimartina** [comment]
@mckaydavis We will also need the certs in the oregon region `us-west-2`...seems like cloudfront (since it is a global service) uses `us-east-1` and then other region-based services (such as ELB) use certs in the current region. Would you mind doing the process again on `us-west-2`? I did request the certs so you should have gotten an email already.

**Comment by mckaydavis** [comment]
@felimartina the request emails went to my spam folder and I missed them so I re-requested and the cert is now issued in `us-west-2`
