### ISSUE TITLE
Add user icon for current location once found.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#74]
![screen shot 2017-11-08 at 6 45 19 pm](https://user-images.githubusercontent.com/949055/32588761-0086d838-c4b5-11e7-9357-a3488957fa35.png)

**Comment by rbvea** [comment]
Note that there's a `locationFound` state in vuex that we could use.

**Comment by rbvea** [comment]
@lelandlopez looks like it's showing up! but I notice that it's going underneath all of the boundaries if it's there.

**Comment by warent** [comment]
Closing as out of date
