### ISSUE TITLE
Run colors through accessibility checkers.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#75]
Green: #6BCE13;
Red: #D45D44;

**Comment by rbvea** [comment]
More colors here: [https://github.com/CodeforHawaii/ACLU/blob/master/design/ACLU_ColorPalette.jpg](https://github.com/CodeforHawaii/ACLU/blob/master/design/ACLU_ColorPalette.jpg)

**Comment by mckaydavis** [comment]
from @tiktnarg: I did run the color pallette thru some contrast checkers and I do think we have a bit of a problem.
Have attached the output from the Chrome accessibility checker, and itʻs clear that we need more contrast between the red, yellow, and green. 
I was thinking, maybe even a scatter print or something?

![image](https://user-images.githubusercontent.com/4591190/34240928-df73f03c-e5b5-11e7-9404-8fd09ea2db98.png)

**Comment by warent** [comment]
Closing as out of date
