### ISSUE TITLE
Import TMK data.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#77]

**Comment by rbvea** [comment]
@ryankanno does this help? https://drive.google.com/drive/u/3/folders/0ByFp918U5axub2t2RTNHdEJ5aGc

**Comment by ryankanno** [comment]
This was completed in 61d7e6f9c2c30b28435643a711cc1a80a969a7c6 and 823639a7efbd797b4b572b06fbaa2bd568f07eb9. Only a portion of the import was run on the development database because throttling.
