### ISSUE TITLE
Add new "category" attribute for each feature.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#81]
To reflect designs, add "category" to a Feature so we can group them on the list pages and detail pages.

Examples: 

* Recreation
* Performance
* Commercial
* Activism
* Religious Ceremony
* Private Land
* Jurisdiction

**Comment by ryankanno** [comment]
This was completed in 116f73bf0b992259ecd939e415cb5e49d0d685e7. Need to create a task to actually fill the "type".
