### ISSUE TITLE
Change location on map pan/zoom.

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#84]
Change the user's location in the vuex store, and query the server when a user moves theirselves on the map.

**Comment by rbvea** [comment]
@nitharios updated the description, let me know if you have any questions, here's where the location is in the vuex store: 

https://github.com/CodeforHawaii/ACLU/blob/master/frontend/src/store/index.js#L8

**Comment by warent** [comment]
Closing as out of date
