### ISSUE TITLE
Merge TMK features

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/ACLU#92]
There are thousands of TMK features that all share the same metadata (private property) and are adjacent. These individual TMK plat map features can be merged into a single feature.  This illustration shows an example:
![image](https://user-images.githubusercontent.com/4591190/35082539-89e350c6-fbbe-11e7-8bda-e976ce4e9b43.png)

I'm going to search for a gdal command to do this.

**Comment by warent** [comment]
Closing as out of date
